project:
  type: website
  output-dir: docs
  resources: pdfjs

website:
  title: ""
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog.qmd
        text: Graduate Projects
      - href: writing.qmd
        text: Undergraduate Projects
        
format:
  html:
    theme: lux
    css: styles.css
    toc: false

editor: visual